version = 1

test_patterns = [
  "tests/test_*.py",
  "**/test_*.py"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  skip_doc_coverage = ["module", "magic", "init"]
  runtime_version = "3.x.x"
